name: Build/Publish
on:
  push:
    branches: 
    - main 
    tags: 
    - v*

jobs:
  build-and-publish-server:
    name: 'Build server'
    runs-on: ubuntu-latest
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Checkout
          uses: actions/checkout@v2
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: 'Build:dockerimage'
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./docker/Dockerfile.actions
            tags: ghcr.io/nmarcetic/gorchase-server:latest
            push: true
            build-args:  |
              - SVC=server
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache-new
        - name: Move cache
          run: |
            rm -rf /tmp/.buildx-cache
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-and-publish-ui:
    name: 'Build ui'
    runs-on: ubuntu-latest
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Checkout
          uses: actions/checkout@v2
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: 'Build:dockerimage'
          uses: docker/build-push-action@v2
          with:
            context: ./ui
            file: ./ui/docker/Dockerfile
            tags: ghcr.io/nmarcetic/gorchase-ui:latest
            push: true
            build-args:  |
              CONFIG=production
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache-new
        - name: Move cache
          run: |
            rm -rf /tmp/.buildx-cache
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache